// Generated by AshTypescript - RPC Actions
// Do not edit this file manually


import type { AshRpcError, ConditionalPaginatedResultMixed, ConversationFilterInput, ConversationResourceSchema, ConversationSortField, InferResult, ModelFilterInput, ModelResourceSchema, ModelSortField, ProviderFilterInput, ProviderResourceSchema, ProviderSortField, SettingFilterInput, SettingResourceSchema, SettingSortField, SortString, UUID, UnifiedFieldSelection, ValidationResult } from "./ash_types";
export type * from "./ash_types";

// Helper Functions

/**
 * Configuration options for action RPC requests
 */
export interface ActionConfig {
  // Request data
  input?: Record<string, any>;
  identity?: any;
  fields?: Array<string | Record<string, any>>; // Field selection
  filter?: Record<string, any>; // Filter options (for reads)
  sort?: string | string[]; // Sort options
  page?:
    | {
        // Offset-based pagination
        limit?: number;
        offset?: number;
        count?: boolean;
      }
    | {
        // Keyset pagination
        limit?: number;
        after?: string;
        before?: string;
      };

  // Metadata
  metadataFields?: ReadonlyArray<string>;

  // HTTP customization
  headers?: Record<string, string>; // Custom headers
  fetchOptions?: RequestInit; // Fetch options (signal, cache, etc.)
  customFetch?: (
    input: RequestInfo | URL,
    init?: RequestInit,
  ) => Promise<Response>;

  // Multitenancy
  tenant?: string; // Tenant parameter

  // Hook context
  hookCtx?: Record<string, any>;
}

/**
 * Configuration options for validation RPC requests
 */
export interface ValidationConfig {
  // Request data
  input?: Record<string, any>;

  // HTTP customization
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (
    input: RequestInfo | URL,
    init?: RequestInit,
  ) => Promise<Response>;

  // Hook context
  hookCtx?: Record<string, any>;
}




/**
 * Gets the CSRF token from the page's meta tag
 * Returns null if no CSRF token is found
 */
export function getPhoenixCSRFToken(): string | null {
  return document
    ?.querySelector("meta[name='csrf-token']")
    ?.getAttribute("content") || null;
}

/**
 * Builds headers object with CSRF token for Phoenix applications
 * Returns headers object with X-CSRF-Token (if available)
 */
export function buildCSRFHeaders(headers: Record<string, string> = {}): Record<string, string> {
  const csrfToken = getPhoenixCSRFToken();
  if (csrfToken) {
    headers["X-CSRF-Token"] = csrfToken;
  }

  return headers;
}

/**
 * Internal helper function for making action RPC requests
 * Handles hooks, request configuration, fetch execution, and error handling
 * @param config Configuration matching ActionConfig
 */
export async function executeActionRpcRequest<T>(
  payload: Record<string, any>,
  config: ActionConfig
): Promise<T> {
    const processedConfig = config;

  const headers: Record<string, string> = {
    "Content-Type": "application/json",
    ...processedConfig.headers,
    ...config.headers,
  };

  const fetchFunction = config.customFetch || processedConfig.customFetch || fetch;
  const fetchOptions: RequestInit = {
    ...processedConfig.fetchOptions,
    ...config.fetchOptions,
    method: "POST",
    headers,
    body: JSON.stringify(payload),
  };

  const response = await fetchFunction("/rpc/run", fetchOptions);
  const result = response.ok ? await response.json() : null;


  if (!response.ok) {
    return {
      success: false,
      errors: [
        {
          type: "network_error",
          message: `Network request failed: ${response.statusText}`,
          shortMessage: "Network error",
          vars: { statusCode: response.status, statusText: response.statusText },
          fields: [],
          path: [],
          details: { statusCode: response.status }
        }
      ],
    } as T;
  }

  return result as T;
}


/**
 * Internal helper function for making validation RPC requests
 * Handles hooks, request configuration, fetch execution, and error handling
 * @param config Configuration matching ValidationConfig
 */
export async function executeValidationRpcRequest<T>(
  payload: Record<string, any>,
  config: ValidationConfig
): Promise<T> {
    const processedConfig = config;

  const headers: Record<string, string> = {
    "Content-Type": "application/json",
    ...processedConfig.headers,
    ...config.headers,
  };

  const fetchFunction = config.customFetch || processedConfig.customFetch || fetch;
  const fetchOptions: RequestInit = {
    ...processedConfig.fetchOptions,
    ...config.fetchOptions,
    method: "POST",
    headers,
    body: JSON.stringify(payload),
  };

  const response = await fetchFunction("/rpc/validate", fetchOptions);
  const result = response.ok ? await response.json() : null;


  if (!response.ok) {
    return {
      success: false,
      errors: [
        {
          type: "network_error",
          message: `Network request failed: ${response.statusText}`,
          shortMessage: "Network error",
          vars: { statusCode: response.status, statusText: response.statusText },
          fields: [],
          path: [],
          details: { statusCode: response.status }
        }
      ],
    } as T;
  }

  return result as T;
}







export type CreateConversationInput = {
  title?: string | null;
  cwd: string;
  model: string;
  systemPrompt?: string | null;
};

export type CreateConversationFields = UnifiedFieldSelection<ConversationResourceSchema>[];

export type InferCreateConversationResult<
  Fields extends CreateConversationFields | undefined,
> = InferResult<ConversationResourceSchema, Fields>;

export type CreateConversationResult<Fields extends CreateConversationFields | undefined = undefined> = | { success: true; data: InferCreateConversationResult<Fields>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Create a new Conversation
 *
 * @ashActionType :create
 */
export async function createConversation<Fields extends CreateConversationFields | undefined = undefined>(
  config: {
  tenant?: string;
  input: CreateConversationInput;
  fields?: Fields;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<CreateConversationResult<Fields extends undefined ? [] : Fields>> {
  const payload = {
    action: "create_conversation",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input,
    ...(config.fields !== undefined && { fields: config.fields })
  };

  return executeActionRpcRequest<CreateConversationResult<Fields extends undefined ? [] : Fields>>(
    payload,
    config
  );
}


/**
 * Validate: Create a new Conversation
 *
 * @ashActionType :create
 * @validation true
 */
export async function validateCreateConversation(
  config: {
  tenant?: string;
  input: CreateConversationInput;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "create_conversation",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


export type DestroyConversationResult = | { success: true; data: {}; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Delete a Conversation
 *
 * @ashActionType :destroy
 */
export async function destroyConversation(
  config: {
  tenant?: string;
  identity: UUID;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<DestroyConversationResult> {
  const payload = {
    action: "destroy_conversation",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    identity: config.identity
  };

  return executeActionRpcRequest<DestroyConversationResult>(
    payload,
    config
  );
}


/**
 * Validate: Delete a Conversation
 *
 * @ashActionType :destroy
 * @validation true
 */
export async function validateDestroyConversation(
  config: {
  tenant?: string;
  identity: UUID | string;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "destroy_conversation",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    identity: config.identity
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


export type GetConversationFields = UnifiedFieldSelection<ConversationResourceSchema>[];
export type InferGetConversationResult<
  Fields extends GetConversationFields,
> = InferResult<ConversationResourceSchema, Fields>;

export type GetConversationResult<Fields extends GetConversationFields> = | { success: true; data: InferGetConversationResult<Fields>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Read Conversation records
 *
 * @ashActionType :read
 */
export async function getConversation<Fields extends GetConversationFields>(
  config: {
  tenant?: string;
  getBy: {
    id: UUID;
  };
  fields: Fields;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<GetConversationResult<Fields>> {
  const payload = {
    action: "get_conversation",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    getBy: config.getBy,
    ...(config.fields !== undefined && { fields: config.fields })
  };

  return executeActionRpcRequest<GetConversationResult<Fields>>(
    payload,
    config
  );
}


/**
 * Validate: Read Conversation records
 *
 * @ashActionType :read
 * @validation true
 */
export async function validateGetConversation(
  config: {
  tenant?: string;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "get_conversation",
    ...(config.tenant !== undefined && { tenant: config.tenant })
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


export type ListConversationsFields = UnifiedFieldSelection<ConversationResourceSchema>[];


export type InferListConversationsResult<
  Fields extends ListConversationsFields | undefined,
  Page extends ListConversationsConfig["page"] = undefined
> = ConditionalPaginatedResultMixed<Page, Array<InferResult<ConversationResourceSchema, Fields>>, {
  results: Array<InferResult<ConversationResourceSchema, Fields>>;
  hasMore: boolean;
  limit: number;
  offset: number;
  count?: number | null;
  type: "offset";
}, {
  results: Array<InferResult<ConversationResourceSchema, Fields>>;
  hasMore: boolean;
  limit: number;
  after: string | null;
  before: string | null;
  previousPage: string;
  nextPage: string;
  count?: number | null;
  type: "keyset";
}>;

export type ListConversationsConfig = {
  tenant?: string;
  fields: ListConversationsFields;
  filter?: ConversationFilterInput;
  sort?: SortString<ConversationSortField> | SortString<ConversationSortField>[];
  page?: (
    {
      limit?: number;
      offset?: number;
      count?: boolean;
    } | {
      limit?: number;
      after?: string;
      before?: string;
    }
  );
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
};

export type ListConversationsResult<Fields extends ListConversationsFields, Page extends ListConversationsConfig["page"] = undefined> = | { success: true; data: InferListConversationsResult<Fields, Page>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Read Conversation records
 *
 * @ashActionType :read
 */
export async function listConversations<Fields extends ListConversationsFields, Config extends ListConversationsConfig = ListConversationsConfig>(
  config: Config & { fields: Fields }
): Promise<ListConversationsResult<Fields, Config["page"]>> {
  const payload = {
    action: "list_conversations",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    ...(config.fields !== undefined && { fields: config.fields }),
    ...(config.filter && { filter: config.filter }),
    ...(config.sort && { sort: Array.isArray(config.sort) ? config.sort.join(",") : config.sort }),
    ...(config.page && { page: config.page })
  };

  return executeActionRpcRequest<ListConversationsResult<Fields, Config["page"]>>(
    payload,
    config
  );
}


/**
 * Validate: Read Conversation records
 *
 * @ashActionType :read
 * @validation true
 */
export async function validateListConversations(
  config: {
  tenant?: string;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "list_conversations",
    ...(config.tenant !== undefined && { tenant: config.tenant })
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


export type UpdateConversationInput = {
  title?: string | null;
  model?: string;
  systemPrompt?: string | null;
};

export type UpdateConversationFields = UnifiedFieldSelection<ConversationResourceSchema>[];

export type InferUpdateConversationResult<
  Fields extends UpdateConversationFields | undefined,
> = InferResult<ConversationResourceSchema, Fields>;

export type UpdateConversationResult<Fields extends UpdateConversationFields | undefined = undefined> = | { success: true; data: InferUpdateConversationResult<Fields>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Update an existing Conversation
 *
 * @ashActionType :update
 */
export async function updateConversation<Fields extends UpdateConversationFields | undefined = undefined>(
  config: {
  tenant?: string;
  identity: UUID;
  input: UpdateConversationInput;
  fields?: Fields;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<UpdateConversationResult<Fields extends undefined ? [] : Fields>> {
  const payload = {
    action: "update_conversation",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    identity: config.identity,
    input: config.input,
    ...(config.fields !== undefined && { fields: config.fields })
  };

  return executeActionRpcRequest<UpdateConversationResult<Fields extends undefined ? [] : Fields>>(
    payload,
    config
  );
}


/**
 * Validate: Update an existing Conversation
 *
 * @ashActionType :update
 * @validation true
 */
export async function validateUpdateConversation(
  config: {
  tenant?: string;
  identity: UUID | string;
  input: UpdateConversationInput;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "update_conversation",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    identity: config.identity,
    input: config.input
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


export type CreateModelInput = {
  spec: string;
  label?: string | null;
  enabled?: boolean;
  position?: number;
};

export type CreateModelFields = UnifiedFieldSelection<ModelResourceSchema>[];

export type InferCreateModelResult<
  Fields extends CreateModelFields | undefined,
> = InferResult<ModelResourceSchema, Fields>;

export type CreateModelResult<Fields extends CreateModelFields | undefined = undefined> = | { success: true; data: InferCreateModelResult<Fields>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Create a new Model
 *
 * @ashActionType :create
 */
export async function createModel<Fields extends CreateModelFields | undefined = undefined>(
  config: {
  tenant?: string;
  input: CreateModelInput;
  fields?: Fields;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<CreateModelResult<Fields extends undefined ? [] : Fields>> {
  const payload = {
    action: "create_model",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input,
    ...(config.fields !== undefined && { fields: config.fields })
  };

  return executeActionRpcRequest<CreateModelResult<Fields extends undefined ? [] : Fields>>(
    payload,
    config
  );
}


/**
 * Validate: Create a new Model
 *
 * @ashActionType :create
 * @validation true
 */
export async function validateCreateModel(
  config: {
  tenant?: string;
  input: CreateModelInput;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "create_model",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


export type DestroyModelResult = | { success: true; data: {}; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Delete a Model
 *
 * @ashActionType :destroy
 */
export async function destroyModel(
  config: {
  tenant?: string;
  identity: UUID;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<DestroyModelResult> {
  const payload = {
    action: "destroy_model",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    identity: config.identity
  };

  return executeActionRpcRequest<DestroyModelResult>(
    payload,
    config
  );
}


/**
 * Validate: Delete a Model
 *
 * @ashActionType :destroy
 * @validation true
 */
export async function validateDestroyModel(
  config: {
  tenant?: string;
  identity: UUID | string;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "destroy_model",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    identity: config.identity
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


export type ListEnabledModelsFields = UnifiedFieldSelection<ModelResourceSchema>[];
export type InferListEnabledModelsResult<
  Fields extends ListEnabledModelsFields,
> = Array<InferResult<ModelResourceSchema, Fields>>;

export type ListEnabledModelsResult<Fields extends ListEnabledModelsFields> = | { success: true; data: InferListEnabledModelsResult<Fields>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Read Model records
 *
 * @ashActionType :read
 */
export async function listEnabledModels<Fields extends ListEnabledModelsFields>(
  config: {
  tenant?: string;
  fields: Fields;
  filter?: ModelFilterInput;
  sort?: SortString<ModelSortField> | SortString<ModelSortField>[];
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ListEnabledModelsResult<Fields>> {
  const payload = {
    action: "list_enabled_models",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    ...(config.fields !== undefined && { fields: config.fields }),
    ...(config.filter && { filter: config.filter }),
    ...(config.sort && { sort: Array.isArray(config.sort) ? config.sort.join(",") : config.sort })
  };

  return executeActionRpcRequest<ListEnabledModelsResult<Fields>>(
    payload,
    config
  );
}


/**
 * Validate: Read Model records
 *
 * @ashActionType :read
 * @validation true
 */
export async function validateListEnabledModels(
  config: {
  tenant?: string;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "list_enabled_models",
    ...(config.tenant !== undefined && { tenant: config.tenant })
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


export type ListModelsFields = UnifiedFieldSelection<ModelResourceSchema>[];
export type InferListModelsResult<
  Fields extends ListModelsFields,
> = Array<InferResult<ModelResourceSchema, Fields>>;

export type ListModelsResult<Fields extends ListModelsFields> = | { success: true; data: InferListModelsResult<Fields>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Read Model records
 *
 * @ashActionType :read
 */
export async function listModels<Fields extends ListModelsFields>(
  config: {
  tenant?: string;
  fields: Fields;
  filter?: ModelFilterInput;
  sort?: SortString<ModelSortField> | SortString<ModelSortField>[];
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ListModelsResult<Fields>> {
  const payload = {
    action: "list_models",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    ...(config.fields !== undefined && { fields: config.fields }),
    ...(config.filter && { filter: config.filter }),
    ...(config.sort && { sort: Array.isArray(config.sort) ? config.sort.join(",") : config.sort })
  };

  return executeActionRpcRequest<ListModelsResult<Fields>>(
    payload,
    config
  );
}


/**
 * Validate: Read Model records
 *
 * @ashActionType :read
 * @validation true
 */
export async function validateListModels(
  config: {
  tenant?: string;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "list_models",
    ...(config.tenant !== undefined && { tenant: config.tenant })
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


export type UpdateModelInput = {
  spec?: string;
  label?: string | null;
  enabled?: boolean;
  position?: number;
};

export type UpdateModelFields = UnifiedFieldSelection<ModelResourceSchema>[];

export type InferUpdateModelResult<
  Fields extends UpdateModelFields | undefined,
> = InferResult<ModelResourceSchema, Fields>;

export type UpdateModelResult<Fields extends UpdateModelFields | undefined = undefined> = | { success: true; data: InferUpdateModelResult<Fields>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Update an existing Model
 *
 * @ashActionType :update
 */
export async function updateModel<Fields extends UpdateModelFields | undefined = undefined>(
  config: {
  tenant?: string;
  identity: UUID;
  input: UpdateModelInput;
  fields?: Fields;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<UpdateModelResult<Fields extends undefined ? [] : Fields>> {
  const payload = {
    action: "update_model",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    identity: config.identity,
    input: config.input,
    ...(config.fields !== undefined && { fields: config.fields })
  };

  return executeActionRpcRequest<UpdateModelResult<Fields extends undefined ? [] : Fields>>(
    payload,
    config
  );
}


/**
 * Validate: Update an existing Model
 *
 * @ashActionType :update
 * @validation true
 */
export async function validateUpdateModel(
  config: {
  tenant?: string;
  identity: UUID | string;
  input: UpdateModelInput;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "update_model",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    identity: config.identity,
    input: config.input
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


export type ClearProviderKeyFields = UnifiedFieldSelection<ProviderResourceSchema>[];

export type InferClearProviderKeyResult<
  Fields extends ClearProviderKeyFields | undefined,
> = InferResult<ProviderResourceSchema, Fields>;

export type ClearProviderKeyResult<Fields extends ClearProviderKeyFields | undefined = undefined> = | { success: true; data: InferClearProviderKeyResult<Fields>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Update an existing Provider
 *
 * @ashActionType :update
 */
export async function clearProviderKey<Fields extends ClearProviderKeyFields | undefined = undefined>(
  config: {
  tenant?: string;
  identity: UUID;
  fields?: Fields;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ClearProviderKeyResult<Fields extends undefined ? [] : Fields>> {
  const payload = {
    action: "clear_provider_key",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    identity: config.identity,
    ...(config.fields !== undefined && { fields: config.fields })
  };

  return executeActionRpcRequest<ClearProviderKeyResult<Fields extends undefined ? [] : Fields>>(
    payload,
    config
  );
}


/**
 * Validate: Update an existing Provider
 *
 * @ashActionType :update
 * @validation true
 */
export async function validateClearProviderKey(
  config: {
  tenant?: string;
  identity: UUID | string;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "clear_provider_key",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    identity: config.identity
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


export type DestroyProviderResult = | { success: true; data: {}; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Delete a Provider
 *
 * @ashActionType :destroy
 */
export async function destroyProvider(
  config: {
  tenant?: string;
  identity: UUID;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<DestroyProviderResult> {
  const payload = {
    action: "destroy_provider",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    identity: config.identity
  };

  return executeActionRpcRequest<DestroyProviderResult>(
    payload,
    config
  );
}


/**
 * Validate: Delete a Provider
 *
 * @ashActionType :destroy
 * @validation true
 */
export async function validateDestroyProvider(
  config: {
  tenant?: string;
  identity: UUID | string;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "destroy_provider",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    identity: config.identity
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


export type ListProvidersFields = UnifiedFieldSelection<ProviderResourceSchema>[];
export type InferListProvidersResult<
  Fields extends ListProvidersFields,
> = Array<InferResult<ProviderResourceSchema, Fields>>;

export type ListProvidersResult<Fields extends ListProvidersFields> = | { success: true; data: InferListProvidersResult<Fields>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Read Provider records
 *
 * @ashActionType :read
 */
export async function listProviders<Fields extends ListProvidersFields>(
  config: {
  tenant?: string;
  fields: Fields;
  filter?: ProviderFilterInput;
  sort?: SortString<ProviderSortField> | SortString<ProviderSortField>[];
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ListProvidersResult<Fields>> {
  const payload = {
    action: "list_providers",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    ...(config.fields !== undefined && { fields: config.fields }),
    ...(config.filter && { filter: config.filter }),
    ...(config.sort && { sort: Array.isArray(config.sort) ? config.sort.join(",") : config.sort })
  };

  return executeActionRpcRequest<ListProvidersResult<Fields>>(
    payload,
    config
  );
}


/**
 * Validate: Read Provider records
 *
 * @ashActionType :read
 * @validation true
 */
export async function validateListProviders(
  config: {
  tenant?: string;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "list_providers",
    ...(config.tenant !== undefined && { tenant: config.tenant })
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


export type PutProviderInput = {
  name: string;
  baseUrl?: string | null;
  label?: string | null;
};

export type PutProviderFields = UnifiedFieldSelection<ProviderResourceSchema>[];

export type InferPutProviderResult<
  Fields extends PutProviderFields | undefined,
> = InferResult<ProviderResourceSchema, Fields>;

export type PutProviderResult<Fields extends PutProviderFields | undefined = undefined> = | { success: true; data: InferPutProviderResult<Fields>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Create a new Provider
 *
 * @ashActionType :create
 */
export async function putProvider<Fields extends PutProviderFields | undefined = undefined>(
  config: {
  tenant?: string;
  input: PutProviderInput;
  fields?: Fields;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<PutProviderResult<Fields extends undefined ? [] : Fields>> {
  const payload = {
    action: "put_provider",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input,
    ...(config.fields !== undefined && { fields: config.fields })
  };

  return executeActionRpcRequest<PutProviderResult<Fields extends undefined ? [] : Fields>>(
    payload,
    config
  );
}


/**
 * Validate: Create a new Provider
 *
 * @ashActionType :create
 * @validation true
 */
export async function validatePutProvider(
  config: {
  tenant?: string;
  input: PutProviderInput;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "put_provider",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


export type SetProviderKeyInput = {
  apiKey?: string | null;
};

export type SetProviderKeyFields = UnifiedFieldSelection<ProviderResourceSchema>[];

export type InferSetProviderKeyResult<
  Fields extends SetProviderKeyFields | undefined,
> = InferResult<ProviderResourceSchema, Fields>;

export type SetProviderKeyResult<Fields extends SetProviderKeyFields | undefined = undefined> = | { success: true; data: InferSetProviderKeyResult<Fields>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Update an existing Provider
 *
 * @ashActionType :update
 */
export async function setProviderKey<Fields extends SetProviderKeyFields | undefined = undefined>(
  config: {
  tenant?: string;
  identity: UUID;
  input?: SetProviderKeyInput;
  fields?: Fields;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<SetProviderKeyResult<Fields extends undefined ? [] : Fields>> {
  const payload = {
    action: "set_provider_key",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    identity: config.identity,
    input: config.input,
    ...(config.fields !== undefined && { fields: config.fields })
  };

  return executeActionRpcRequest<SetProviderKeyResult<Fields extends undefined ? [] : Fields>>(
    payload,
    config
  );
}


/**
 * Validate: Update an existing Provider
 *
 * @ashActionType :update
 * @validation true
 */
export async function validateSetProviderKey(
  config: {
  tenant?: string;
  identity: UUID | string;
  input?: SetProviderKeyInput;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "set_provider_key",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    identity: config.identity,
    input: config.input
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


export type ListSettingsFields = UnifiedFieldSelection<SettingResourceSchema>[];


export type InferListSettingsResult<
  Fields extends ListSettingsFields | undefined,
  Page extends ListSettingsConfig["page"] = undefined
> = ConditionalPaginatedResultMixed<Page, Array<InferResult<SettingResourceSchema, Fields>>, {
  results: Array<InferResult<SettingResourceSchema, Fields>>;
  hasMore: boolean;
  limit: number;
  offset: number;
  count?: number | null;
  type: "offset";
}, {
  results: Array<InferResult<SettingResourceSchema, Fields>>;
  hasMore: boolean;
  limit: number;
  after: string | null;
  before: string | null;
  previousPage: string;
  nextPage: string;
  count?: number | null;
  type: "keyset";
}>;

export type ListSettingsConfig = {
  tenant?: string;
  fields: ListSettingsFields;
  filter?: SettingFilterInput;
  sort?: SortString<SettingSortField> | SortString<SettingSortField>[];
  page?: (
    {
      limit?: number;
      offset?: number;
      count?: boolean;
    } | {
      limit?: number;
      after?: string;
      before?: string;
    }
  );
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
};

export type ListSettingsResult<Fields extends ListSettingsFields, Page extends ListSettingsConfig["page"] = undefined> = | { success: true; data: InferListSettingsResult<Fields, Page>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Read Setting records
 *
 * @ashActionType :read
 */
export async function listSettings<Fields extends ListSettingsFields, Config extends ListSettingsConfig = ListSettingsConfig>(
  config: Config & { fields: Fields }
): Promise<ListSettingsResult<Fields, Config["page"]>> {
  const payload = {
    action: "list_settings",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    ...(config.fields !== undefined && { fields: config.fields }),
    ...(config.filter && { filter: config.filter }),
    ...(config.sort && { sort: Array.isArray(config.sort) ? config.sort.join(",") : config.sort }),
    ...(config.page && { page: config.page })
  };

  return executeActionRpcRequest<ListSettingsResult<Fields, Config["page"]>>(
    payload,
    config
  );
}


/**
 * Validate: Read Setting records
 *
 * @ashActionType :read
 * @validation true
 */
export async function validateListSettings(
  config: {
  tenant?: string;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "list_settings",
    ...(config.tenant !== undefined && { tenant: config.tenant })
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


export type PutSettingInput = {
  key: string;
  value?: string | null;
};

export type PutSettingFields = UnifiedFieldSelection<SettingResourceSchema>[];

export type InferPutSettingResult<
  Fields extends PutSettingFields | undefined,
> = InferResult<SettingResourceSchema, Fields>;

export type PutSettingResult<Fields extends PutSettingFields | undefined = undefined> = | { success: true; data: InferPutSettingResult<Fields>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Create a new Setting
 *
 * @ashActionType :create
 */
export async function putSetting<Fields extends PutSettingFields | undefined = undefined>(
  config: {
  tenant?: string;
  input: PutSettingInput;
  fields?: Fields;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<PutSettingResult<Fields extends undefined ? [] : Fields>> {
  const payload = {
    action: "put_setting",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input,
    ...(config.fields !== undefined && { fields: config.fields })
  };

  return executeActionRpcRequest<PutSettingResult<Fields extends undefined ? [] : Fields>>(
    payload,
    config
  );
}


/**
 * Validate: Create a new Setting
 *
 * @ashActionType :create
 * @validation true
 */
export async function validatePutSetting(
  config: {
  tenant?: string;
  input: PutSettingInput;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "put_setting",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


export type UpdateSettingInput = {
  value?: string | null;
};

export type UpdateSettingFields = UnifiedFieldSelection<SettingResourceSchema>[];

export type InferUpdateSettingResult<
  Fields extends UpdateSettingFields | undefined,
> = InferResult<SettingResourceSchema, Fields>;

export type UpdateSettingResult<Fields extends UpdateSettingFields | undefined = undefined> = | { success: true; data: InferUpdateSettingResult<Fields>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Update an existing Setting
 *
 * @ashActionType :update
 */
export async function updateSetting<Fields extends UpdateSettingFields | undefined = undefined>(
  config: {
  tenant?: string;
  identity: UUID;
  input?: UpdateSettingInput;
  fields?: Fields;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<UpdateSettingResult<Fields extends undefined ? [] : Fields>> {
  const payload = {
    action: "update_setting",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    identity: config.identity,
    input: config.input,
    ...(config.fields !== undefined && { fields: config.fields })
  };

  return executeActionRpcRequest<UpdateSettingResult<Fields extends undefined ? [] : Fields>>(
    payload,
    config
  );
}


/**
 * Validate: Update an existing Setting
 *
 * @ashActionType :update
 * @validation true
 */
export async function validateUpdateSetting(
  config: {
  tenant?: string;
  identity: UUID | string;
  input?: UpdateSettingInput;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "update_setting",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    identity: config.identity,
    input: config.input
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}

