// Self-heal stale Phoenix CSRF tokens.
//
// The SPA reads the CSRF token from a static <meta name="csrf-token"> baked
// into the page at load. A tab left open across a deploy — or a browser
// serving a cached index.html — carries a token that no longer matches the
// session, so RPC POSTs come back 403 and the sidebar/data silently fail to
// load. Rather than force a hard reload, intercept 403s from any /rpc/ call,
// fetch a fresh token for the current session, update the meta tag, and retry
// the request once.
//
// Hand-written (the ash_typescript-generated ash_rpc.ts is regenerated by
// codegen, so the fix must live outside it).

export function installCsrfRetry(): void {
  const original = window.fetch.bind(window);

  window.fetch = async (input: RequestInfo | URL, init?: RequestInit): Promise<Response> => {
    const response = await original(input, init);

    if (!shouldRetry(response, input, init)) return response;

    const token = await refreshToken(original);
    if (!token) return response;

    const headers = new Headers(init?.headers);
    headers.set("X-CSRF-Token", token);
    headers.set("X-CSRF-Retry", "1");
    return original(input, { ...init, headers });
  };
}

function shouldRetry(response: Response, input: RequestInfo | URL, init?: RequestInit): boolean {
  if (response.status !== 403) return false;
  const url = requestUrl(input);
  if (!url.includes("/rpc/") || url.includes("/rpc/csrf")) return false;
  // Retry at most once.
  return !(init?.headers && new Headers(init.headers).has("X-CSRF-Retry"));
}

function requestUrl(input: RequestInfo | URL): string {
  if (typeof input === "string") return input;
  if (input instanceof URL) return input.toString();
  return input.url;
}

async function refreshToken(fetchFn: typeof fetch): Promise<string | null> {
  try {
    const res = await fetchFn("/rpc/csrf", { headers: { Accept: "application/json" } });
    if (!res.ok) return null;
    const { token } = await res.json();
    if (typeof token === "string" && token !== "") {
      document.querySelector("meta[name='csrf-token']")?.setAttribute("content", token);
      return token;
    }
  } catch {
    // Network/JSON failure — nothing to retry with.
  }
  return null;
}
