#!/usr/bin/env bash
#
# longpi installer — downloads the Linux release and runs it as a systemd user
# service. Configuration lives in a FILE (~/.config/longpi/config.jsonc), never
# environment variables; secrets are generated by the server on first boot.
#
#   curl -fsSL https://raw.githubusercontent.com/mjason/longpi/main/install.sh | bash
#   ./install.sh [vX.Y.Z]        # specific version (default: latest)
set -euo pipefail

REPO="${LONGPI_REPO:-mjason/longpi}"
ROOT="${LONGPI_HOME:-$HOME/.local/longpi}"
DATA_DIR="${LONGPI_DATA_DIR:-$HOME/.local/share/longpi}"
CONFIG_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/longpi"
CONFIG_FILE="$CONFIG_DIR/config.jsonc"
SERVICE_NAME="${LONGPI_SERVICE:-longpi}"
SERVICE_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/systemd/user"
PORT="${LONGPI_PORT:-4080}"

say() { printf '\033[1;32m==>\033[0m %s\n' "$*"; }
die() { printf '\033[1;31merror:\033[0m %s\n' "$*" >&2; exit 1; }

command -v curl >/dev/null || die "curl is required"
command -v tar >/dev/null || die "tar is required"

case "$(uname -s)/$(uname -m)" in
  Linux/x86_64) PLATFORM="linux-x86_64" ;;
  *) die "no prebuilt release for $(uname -s)/$(uname -m) (Linux/x86_64 only for now)" ;;
esac
command -v systemctl >/dev/null || die "systemd (systemctl --user) is required"

# The extension host runs via bun; the service needs it on PATH.
BUN_BIN="$(command -v bun || true)"
[ -n "$BUN_BIN" ] || BUN_BIN="$HOME/.local/share/reflex/bun/bin/bun"
BUN_DIR="$(dirname "$BUN_BIN")"
[ -x "$BUN_BIN" ] || say "warning: bun not found — extensions will be disabled until 'bun' is on PATH"

# --- resolve version ---------------------------------------------------------
TAG="${1:-}"
if [ -z "$TAG" ]; then
  say "resolving latest release of $REPO"
  TAG=$(curl -fsSL "https://api.github.com/repos/$REPO/releases?per_page=15" |
    grep '"tag_name"' | cut -d'"' -f4 | grep -m1 '^v[0-9]') || true
  [ -n "$TAG" ] || die "could not resolve the latest release (does $REPO have releases?)"
fi
ASSET="longpi-$TAG-$PLATFORM.tar.gz"
URL="https://github.com/$REPO/releases/download/$TAG/$ASSET"
DEST="$ROOT/versions/$TAG"

# --- download + verify + unpack ----------------------------------------------
if [ -x "$DEST/bin/longpi" ]; then
  say "$TAG already downloaded"
else
  say "downloading $ASSET"
  TMP=$(mktemp -d); trap 'rm -rf "$TMP"' EXIT
  curl -fSL --progress-bar -o "$TMP/$ASSET" "$URL"
  if curl -fsSL -o "$TMP/$ASSET.sha256" "$URL.sha256" 2>/dev/null; then
    (cd "$TMP" && sha256sum -c "$ASSET.sha256" >/dev/null) || die "checksum mismatch"
    say "checksum ok"
  fi
  mkdir -p "$DEST"
  tar -xzf "$TMP/$ASSET" -C "$DEST"
fi

# --- configuration (first install only) --------------------------------------
# LONGPI_AUTH="email:password" enables sign-in on first install: the account is
# written straight to the database (never to a config file) and config.jsonc
# only carries "auth": {"enabled": true}.
mkdir -p "$DATA_DIR" "$CONFIG_DIR" "$SERVICE_DIR"
AUTH_BLOCK=""
if [ -n "${LONGPI_AUTH:-}" ]; then
  AUTH_BLOCK='
  // Sign-in required. Accounts live in the database — manage them with:
  //   ~/.local/longpi/current/bin/longpi eval '"'"'Longpi.Release.add_user("a@b.c", "pw")'"'"'
  "auth": { "enabled": true },'
fi
if [ ! -f "$CONFIG_FILE" ]; then
  say "writing $CONFIG_FILE"
  cat > "$CONFIG_FILE" <<CFGEOF
{
  // longpi server configuration. Restart the service after editing.
  "server": true,
  "port": $PORT,
  // Loopback only by default. LAN access: "0.0.0.0".
  "listenIp": "127.0.0.1",
  "host": "localhost",
  "scheme": "http",
  // Enable when behind a reverse proxy reached by a real hostname.
  "checkOrigin": false,$AUTH_BLOCK
  "poolSize": 10
}
CFGEOF
  chmod 600 "$CONFIG_FILE"
else
  say "keeping existing $CONFIG_FILE"
fi

# --- service -----------------------------------------------------------------
ln -sfn "$DEST" "$ROOT/current"

say "installing systemd user service"
cat > "$SERVICE_DIR/$SERVICE_NAME.service" <<EOF
[Unit]
Description=longpi
After=network-online.target

[Service]
Type=exec
Environment=PATH=$BUN_DIR:/usr/local/bin:/usr/bin:/bin
ExecStartPre=$ROOT/current/bin/longpi eval "Longpi.Release.migrate()"
ExecStart=$ROOT/current/bin/longpi start
ExecStop=$ROOT/current/bin/longpi stop
Restart=on-failure
RestartSec=2
KillMode=process

[Install]
WantedBy=default.target
EOF

# First-run account, BEFORE the service starts (an auth-enabled boot with zero
# accounts refuses to start). Password goes straight to the database.
if [ -n "${LONGPI_AUTH:-}" ]; then
  AUTH_EMAIL="${LONGPI_AUTH%%:*}"
  AUTH_PASS="${LONGPI_AUTH#*:}"
  say "creating account $AUTH_EMAIL"
  "$ROOT/current/bin/longpi" eval "Longpi.Release.add_user(~s($AUTH_EMAIL), ~s($AUTH_PASS))" ||
    die "could not create the account (password must be at least 8 characters)"
fi

systemctl --user daemon-reload
systemctl --user enable "$SERVICE_NAME" >/dev/null 2>&1 || true
say "starting $SERVICE_NAME ($TAG)"
systemctl --user restart "$SERVICE_NAME"
loginctl enable-linger "$USER" 2>/dev/null || true

# --- prune old versions (keep 3) --------------------------------------------
ls -1dt "$ROOT"/versions/* 2>/dev/null | tail -n +4 | while read -r old; do
  [ "$old" = "$DEST" ] && continue
  say "pruning $(basename "$old")"
  rm -rf "$old"
done

# --- health check ------------------------------------------------------------
PORT_NOW=$(grep -oE '"port"[[:space:]]*:[[:space:]]*[0-9]+' "$CONFIG_FILE" | grep -oE '[0-9]+' | head -1)
PORT_NOW="${PORT_NOW:-$PORT}"
for _ in $(seq 1 20); do
  if curl -fsS -o /dev/null "http://127.0.0.1:$PORT_NOW/"; then
    say "longpi $TAG is up at http://localhost:$PORT_NOW"
    exit 0
  fi
  sleep 1
done
die "service started but did not answer on :$PORT_NOW — check: journalctl --user -u $SERVICE_NAME -e"
