import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :longpi, LongpiWeb.Endpoint, cache_static_manifest: "priv/static/cache_manifest.json"

# No force_ssl: longpi serves plain http on localhost/LAN by design (the listen
# address is opt-in via "listenIp" in config.jsonc). TLS termination, when
# wanted, belongs to a reverse proxy in front (set "scheme": "https" and
# "checkOrigin": true there).

# Configure Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Req

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
