defmodule Longpi.Repo.Migrations.AddProviders do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:providers, primary_key: false) do
      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :api_key, :text
      add :base_url, :text
      add :name, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create unique_index(:providers, [:name], name: "providers_unique_name_index")
  end

  def down do
    drop_if_exists unique_index(:providers, [:name], name: "providers_unique_name_index")

    drop table(:providers)
  end
end
