defmodule Longpi.Repo.Migrations.AddModelContextWindow do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:models) do
      add :context_window, :bigint
    end
  end

  def down do
    alter table(:models) do
      remove :context_window
    end
  end
end
