defmodule Longpi.Repo.Migrations.AddTurnStartedAt do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:conversations) do
      add :turn_started_at, :utc_datetime_usec
    end
  end

  def down do
    alter table(:conversations) do
      remove :turn_started_at
    end
  end
end