defmodule Longpi.Repo.Migrations.AddMessageConversationIndex do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create index(:conversation_messages, ["conversation_id", "position"])
  end

  def down do
    drop_if_exists index(:conversation_messages, ["conversation_id", "position"],
                     name: "conversation_messages_conversation_id_position_index"
                   )
  end
end