defmodule Longpi.Repo.Migrations.AddProviderLabel do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:providers) do
      add :label, :text
    end
  end

  def down do
    alter table(:providers) do
      remove :label
    end
  end
end
