defmodule Longpi.Repo.Migrations.AddAliasReasoningEffort do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:model_aliases) do
      add :reasoning_effort, :text
    end
  end

  def down do
    alter table(:model_aliases) do
      remove :reasoning_effort
    end
  end
end