defmodule Longpi.Repo.Migrations.AddMessageModel do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:conversation_messages) do
      add :model, :text
    end
  end

  def down do
    alter table(:conversation_messages) do
      remove :model
    end
  end
end