defmodule Longpi.Repo.Migrations.AddUnseenAttention do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:conversations) do
      add :unseen_at, :utc_datetime_usec
      add :unseen_kind, :text
    end
  end

  def down do
    alter table(:conversations) do
      remove :unseen_kind
      remove :unseen_at
    end
  end
end