defmodule Longpi.Repo.Migrations.AddModelAliases do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:model_aliases, primary_key: false) do
      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :note, :text
      add :spec, :text, null: false
      add :name, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create unique_index(:model_aliases, [:name], name: "model_aliases_unique_name_index")
  end

  def down do
    drop_if_exists unique_index(:model_aliases, [:name], name: "model_aliases_unique_name_index")

    drop table(:model_aliases)
  end
end