defmodule Longpi.Repo.Migrations.AddModels do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:models, primary_key: false) do
      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :position, :bigint, null: false
      add :enabled, :boolean, null: false
      add :label, :text
      add :spec, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create unique_index(:models, [:spec], name: "models_unique_spec_index")
  end

  def down do
    drop_if_exists unique_index(:models, [:spec], name: "models_unique_spec_index")

    drop table(:models)
  end
end
