defmodule Longpi.Repo.Migrations.AddConversations do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:conversations, primary_key: false) do
      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :model, :text, null: false
      add :cwd, :text, null: false
      add :title, :text
      add :id, :uuid, null: false, primary_key: true
    end

    create table(:conversation_messages, primary_key: false) do
      add :conversation_id,
          references(:conversations,
            column: :id,
            name: "conversation_messages_conversation_id_fkey",
            type: :uuid
          ),
          null: false

      add :inserted_at, :utc_datetime_usec, null: false
      add :position, :bigint, null: false
      add :error, :boolean, null: false
      add :tool_name, :text
      add :tool_call_id, :text
      add :tool_calls, {:array, :map}, null: false, default: []
      add :content, :text, null: false
      add :role, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end
  end

  def down do
    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `conversation_messages` table without the `conversation_messages_conversation_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop table(:conversation_messages)

    drop table(:conversations)
  end
end
