defmodule Longpi.Repo.Migrations.AddScheduledTasks do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:scheduled_tasks, primary_key: false) do
      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :last_run_at, :utc_datetime
      add :enabled, :boolean, null: false
      add :task, :text, null: false
      add :cron, :text, null: false
      add :conversation_id, :uuid, null: false
      add :id, :uuid, null: false, primary_key: true
    end
  end

  def down do
    drop table(:scheduled_tasks)
  end
end