defmodule Longpi.Repo.Migrations.AddSubagentFields do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:conversations) do
      add :agent_role, :text

      add :parent_id,
          references(:conversations,
            column: :id,
            name: "conversations_parent_id_fkey",
            type: :uuid
          )
    end
  end

  def down do
    alter table(:conversations) do
      remove :parent_id
      remove :agent_role
    end

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `conversations` table without the `conversations_parent_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."
  end
end