defmodule Longpi.Repo.Migrations.AddCompactions do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:compactions, primary_key: false) do
      add :conversation_id,
          references(:conversations,
            column: :id,
            name: "compactions_conversation_id_fkey",
            type: :uuid
          ),
          null: false

      add :inserted_at, :utc_datetime_usec, null: false
      add :input_tokens, :bigint
      add :covered_through, :bigint, null: false
      add :summary, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end
  end

  def down do
    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `compactions` table without the `compactions_conversation_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop table(:compactions)
  end
end
