defmodule Longpi.Repo.Migrations.AddSettingsAndPromptOverride do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:settings, primary_key: false) do
      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :value, :text
      add :key, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create unique_index(:settings, [:key], name: "settings_unique_key_index")

    alter table(:conversations) do
      add :system_prompt, :text
    end
  end

  def down do
    alter table(:conversations) do
      remove :system_prompt
    end

    drop_if_exists unique_index(:settings, [:key], name: "settings_unique_key_index")

    drop table(:settings)
  end
end
